# Your full site URL
baseURL = "https://sophieis.lgbt/"
languageCode = "en-us"

# Title of your site
title = "Sophie's Space"
# How many feed entries to load at once
paginate = 6

[taxonomies]
tag = "tags"

[author]
name = "Sophie 🌸"
# Your profile image. External link or relative to static/. Examples:
# "https://imgur.com/123456788"
# "image/me.webp"
image = ""
about = "Gender? I hardly even know her!"
email = "sophie@sophieis.lgbt"

[params]
# Name of a file in static/skins/ without the ".css" extension
skin = "macintosh"

# Totally optional cool stuff (see README for details)
# socialImage = "static/img/social.png" # site image for rich embeds
# customCSS = "css/style.css" # relative to ./static/
# plausible = true
# paymentPointer = "$wallet.provider.com/myspecialid123"
# webmentionUrl = "https://webmention.io/example/webmention"
# pingbackUrl = "https://webmention.io/example/xmlrpc"
# micropubUrl = "https://example.com/.netlify/functions/micropub"
# microsubUrl = "https://aperture.p3k.io/microsub/example"


# For IndieAuth and the author card
githubuser = "sophienyaa"
twitteruser = "nyaasophie" # no @ in front
mastodon = "https://tech.lgbt/@sophienyaa" # full link to your instance profile

[permalinks]
# Format for feed entry links. You probably don't need to change this.
feed = "/:title/"

[outputs]
# Output formats for your feed. You probably don't need to change this.
  home = ["HTML", "JSON", "RSS"]